// Code generated by protoc-gen-go-rest. DO NOT EDIT.
// versions:
// - protoc-gen-go-rest v0.0.0-alpha.0
// - protoc             v7.34.0
// source: gateway.proto

package rest

import (
	embed "embed"
)

//go:embed gateway_swagger.json
var swaggerFile embed.FS

func GetGatewaySwagger() []byte {
	js, err := swaggerFile.ReadFile("gateway_swagger.json")
	if err != nil {
		return []byte("{}")
	}

	return js
}
