// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gateway.proto

package api

import (
	_ "github.com/merzzzl/proto-rest-api/restapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node is one full entry in the mesh node database.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                                  // node number (primary key)
	LongName      string                 `protobuf:"bytes,2,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`         // human-readable long name
	ShortName     string                 `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`      // short name / call sign
	HwModel       string                 `protobuf:"bytes,4,opt,name=hw_model,json=hwModel,proto3" json:"hw_model,omitempty"`            // hardware model
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                                 // device role
	Snr           float32                `protobuf:"fixed32,6,opt,name=snr,proto3" json:"snr,omitempty"`                                 // signal-to-noise ratio of the last packet, dB
	Rssi          int32                  `protobuf:"varint,7,opt,name=rssi,proto3" json:"rssi,omitempty"`                                // received signal strength of the last packet, dBm
	HopsAway      *uint32                `protobuf:"varint,8,opt,name=hops_away,json=hopsAway,proto3,oneof" json:"hops_away,omitempty"`  // hops away from us; absent if unknown
	Latitude      *float64               `protobuf:"fixed64,9,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`                 // latitude, degrees; absent if unknown
	Longitude     *float64               `protobuf:"fixed64,10,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`              // longitude, degrees; absent if unknown
	Altitude      *int32                 `protobuf:"varint,11,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`                 // altitude, metres; absent if unknown
	Battery       *uint32                `protobuf:"varint,12,opt,name=battery,proto3,oneof" json:"battery,omitempty"`                   // battery level, percent; absent if unknown
	Voltage       *float32               `protobuf:"fixed32,13,opt,name=voltage,proto3,oneof" json:"voltage,omitempty"`                  // battery voltage, volts; absent if unknown
	ViaMqtt       bool                   `protobuf:"varint,14,opt,name=via_mqtt,json=viaMqtt,proto3" json:"via_mqtt,omitempty"`          // true if last seen over MQTT rather than LoRa
	IsFavorite    bool                   `protobuf:"varint,15,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"` // true if marked favorite on the radio
	LastHeard     int64                  `protobuf:"varint,16,opt,name=last_heard,json=lastHeard,proto3" json:"last_heard,omitempty"`    // last time a packet was heard, Unix seconds
	UpdatedAt     int64                  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // last time this record changed, Unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Node) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *Node) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Node) GetHwModel() string {
	if x != nil {
		return x.HwModel
	}
	return ""
}

func (x *Node) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Node) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *Node) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *Node) GetHopsAway() uint32 {
	if x != nil && x.HopsAway != nil {
		return *x.HopsAway
	}
	return 0
}

func (x *Node) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Node) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Node) GetAltitude() int32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *Node) GetBattery() uint32 {
	if x != nil && x.Battery != nil {
		return *x.Battery
	}
	return 0
}

func (x *Node) GetVoltage() float32 {
	if x != nil && x.Voltage != nil {
		return *x.Voltage
	}
	return 0
}

func (x *Node) GetViaMqtt() bool {
	if x != nil {
		return x.ViaMqtt
	}
	return false
}

func (x *Node) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Node) GetLastHeard() int64 {
	if x != nil {
		return x.LastHeard
	}
	return 0
}

func (x *Node) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// NodeSummary is the compact node entry returned by the list endpoint.
type NodeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                             // node number (primary key)
	ShortName     string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"` // short name / call sign
	LongName      string                 `protobuf:"bytes,3,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`    // human-readable long name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSummary) Reset() {
	*x = NodeSummary{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSummary) ProtoMessage() {}

func (x *NodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSummary.ProtoReflect.Descriptor instead.
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSummary) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NodeSummary) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *NodeSummary) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

// Message is one received text message with all stored metadata.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // on-air Meshtastic packet id (primary key)
	From          uint32                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`                               // sender node number
	To            uint32                 `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`                                   // recipient node number (0xffffffff for broadcast)
	Channel       uint32                 `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`                         // channel index the message was received on
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`                                // message body text
	Snr           float32                `protobuf:"fixed32,7,opt,name=snr,proto3" json:"snr,omitempty"`                                // signal-to-noise ratio of the received packet, dB
	Rssi          int32                  `protobuf:"varint,8,opt,name=rssi,proto3" json:"rssi,omitempty"`                               // received signal strength, dBm
	HopsAway      *uint32                `protobuf:"varint,9,opt,name=hops_away,json=hopsAway,proto3,oneof" json:"hops_away,omitempty"` // hops traversed (hop_start - hop_limit); absent if unknown
	RxTime        int64                  `protobuf:"varint,10,opt,name=rx_time,json=rxTime,proto3" json:"rx_time,omitempty"`            // receive time, Unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *Message) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *Message) GetHopsAway() uint32 {
	if x != nil && x.HopsAway != nil {
		return *x.HopsAway
	}
	return 0
}

func (x *Message) GetRxTime() int64 {
	if x != nil {
		return x.RxTime
	}
	return 0
}

// ListNodesRequest is the (empty) request for the node list.
type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

// ListNodesResponse carries the node summaries.
type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSummary         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // node summaries, most recently heard first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ListNodesResponse) GetNodes() []*NodeSummary {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// GetNodeRequest selects one node for the detail endpoint.
type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"` // node number (path)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// ListMessagesResponse carries the messages for a node.
type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // messages, newest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ListMessagesRequest selects the sender node for the direct-message list.
type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"` // sender node number (path)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// SendMessageRequest is a text message to transmit to one node.
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                              // recipient node number (path)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                             // message body text
	Channel       *uint32                `protobuf:"varint,3,opt,name=channel,proto3,oneof" json:"channel,omitempty"`                // channel index (0 by default)
	ReplyId       *uint32                `protobuf:"varint,4,opt,name=reply_id,json=replyId,proto3,oneof" json:"reply_id,omitempty"` // packet id this message replies to (0 = none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetChannel() uint32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

func (x *SendMessageRequest) GetReplyId() uint32 {
	if x != nil && x.ReplyId != nil {
		return *x.ReplyId
	}
	return 0
}

// RegisterCallbackRequest registers a webhook URL.
type RegisterCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // webhook URL to register
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCallbackRequest) Reset() {
	*x = RegisterCallbackRequest{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCallbackRequest) ProtoMessage() {}

func (x *RegisterCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCallbackRequest.ProtoReflect.Descriptor instead.
func (*RegisterCallbackRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterCallbackRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ListCallbacksRequest is the (empty) request for the callback list.
type ListCallbacksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallbacksRequest) Reset() {
	*x = ListCallbacksRequest{}
	mi := &file_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallbacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallbacksRequest) ProtoMessage() {}

func (x *ListCallbacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallbacksRequest.ProtoReflect.Descriptor instead.
func (*ListCallbacksRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{10}
}

// ListCallbacksResponse carries the registered callbacks.
type ListCallbacksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"` // registered webhook subscriptions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallbacksResponse) Reset() {
	*x = ListCallbacksResponse{}
	mi := &file_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallbacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallbacksResponse) ProtoMessage() {}

func (x *ListCallbacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallbacksResponse.ProtoReflect.Descriptor instead.
func (*ListCallbacksResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *ListCallbacksResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// DeleteCallbackRequest unregisters a webhook URL.
type DeleteCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // webhook URL to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCallbackRequest) Reset() {
	*x = DeleteCallbackRequest{}
	mi := &file_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCallbackRequest) ProtoMessage() {}

func (x *DeleteCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCallbackRequest.ProtoReflect.Descriptor instead.
func (*DeleteCallbackRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCallbackRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Channel is one configured channel on the connected radio.
type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // channel index
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`    // channel name
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`    // channel role (e.g. PRIMARY, SECONDARY, DISABLED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *Channel) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// ListChannelsRequest is the (empty) request for the channel list.
type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{14}
}

// ListChannelsResponse carries the configured channels.
type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"` // configured channels, ordered by index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

// ListChannelMessagesRequest selects a channel for its message list.
type ListChannelMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // channel index (path)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelMessagesRequest) Reset() {
	*x = ListChannelMessagesRequest{}
	mi := &file_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelMessagesRequest) ProtoMessage() {}

func (x *ListChannelMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChannelMessagesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ListChannelMessagesRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// SendChannelMessageRequest is a text message to broadcast on one channel.
type SendChannelMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                          // channel index (path)
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                             // message body text
	ReplyId       *uint32                `protobuf:"varint,3,opt,name=reply_id,json=replyId,proto3,oneof" json:"reply_id,omitempty"` // packet id this message replies to (0 = none)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelMessageRequest) Reset() {
	*x = SendChannelMessageRequest{}
	mi := &file_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelMessageRequest) ProtoMessage() {}

func (x *SendChannelMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChannelMessageRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *SendChannelMessageRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SendChannelMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendChannelMessageRequest) GetReplyId() uint32 {
	if x != nil && x.ReplyId != nil {
		return *x.ReplyId
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x04rest\x1a\x19restapi/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb6\x04\n" +
	"\x04Node\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\x12\x1b\n" +
	"\tlong_name\x18\x02 \x01(\tR\blongName\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12\x19\n" +
	"\bhw_model\x18\x04 \x01(\tR\ahwModel\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x10\n" +
	"\x03snr\x18\x06 \x01(\x02R\x03snr\x12\x12\n" +
	"\x04rssi\x18\a \x01(\x05R\x04rssi\x12 \n" +
	"\thops_away\x18\b \x01(\rH\x00R\bhopsAway\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\t \x01(\x01H\x01R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\n" +
	" \x01(\x01H\x02R\tlongitude\x88\x01\x01\x12\x1f\n" +
	"\baltitude\x18\v \x01(\x05H\x03R\baltitude\x88\x01\x01\x12\x1d\n" +
	"\abattery\x18\f \x01(\rH\x04R\abattery\x88\x01\x01\x12\x1d\n" +
	"\avoltage\x18\r \x01(\x02H\x05R\avoltage\x88\x01\x01\x12\x19\n" +
	"\bvia_mqtt\x18\x0e \x01(\bR\aviaMqtt\x12\x1f\n" +
	"\vis_favorite\x18\x0f \x01(\bR\n" +
	"isFavorite\x12\x1d\n" +
	"\n" +
	"last_heard\x18\x10 \x01(\x03R\tlastHeard\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAtB\f\n" +
	"\n" +
	"_hops_awayB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\v\n" +
	"\t_altitudeB\n" +
	"\n" +
	"\b_batteryB\n" +
	"\n" +
	"\b_voltage\"[\n" +
	"\vNodeSummary\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x1b\n" +
	"\tlong_name\x18\x03 \x01(\tR\blongName\"\xda\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\rR\x02to\x12\x18\n" +
	"\achannel\x18\x05 \x01(\rR\achannel\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x10\n" +
	"\x03snr\x18\a \x01(\x02R\x03snr\x12\x12\n" +
	"\x04rssi\x18\b \x01(\x05R\x04rssi\x12 \n" +
	"\thops_away\x18\t \x01(\rH\x00R\bhopsAway\x88\x01\x01\x12\x17\n" +
	"\arx_time\x18\n" +
	" \x01(\x03R\x06rxTimeB\f\n" +
	"\n" +
	"_hops_away\"\x12\n" +
	"\x10ListNodesRequest\"<\n" +
	"\x11ListNodesResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.rest.NodeSummaryR\x05nodes\"\"\n" +
	"\x0eGetNodeRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\"A\n" +
	"\x14ListMessagesResponse\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.rest.MessageR\bmessages\"'\n" +
	"\x13ListMessagesRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\"\x92\x01\n" +
	"\x12SendMessageRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\achannel\x18\x03 \x01(\rH\x00R\achannel\x88\x01\x01\x12\x1e\n" +
	"\breply_id\x18\x04 \x01(\rH\x01R\areplyId\x88\x01\x01B\n" +
	"\n" +
	"\b_channelB\v\n" +
	"\t_reply_id\"+\n" +
	"\x17RegisterCallbackRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x16\n" +
	"\x14ListCallbacksRequest\"+\n" +
	"\x15ListCallbacksResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\")\n" +
	"\x15DeleteCallbackRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"G\n" +
	"\aChannel\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x15\n" +
	"\x13ListChannelsRequest\"A\n" +
	"\x14ListChannelsResponse\x12)\n" +
	"\bchannels\x18\x01 \x03(\v2\r.rest.ChannelR\bchannels\"2\n" +
	"\x1aListChannelMessagesRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"r\n" +
	"\x19SendChannelMessageRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\breply_id\x18\x03 \x01(\rH\x00R\areplyId\x88\x01\x01B\v\n" +
	"\t_reply_id2\x83\x06\n" +
	"\vMeshService\x12W\n" +
	"\tListNodes\x12\x16.rest.ListNodesRequest\x1a\x17.rest.ListNodesResponse\"\x19\x8a\x97\"\x15\n" +
	"\x03GET\x12\x06/nodes\"\x06.nodes\x12F\n" +
	"\aGetNode\x12\x14.rest.GetNodeRequest\x1a\n" +
	".rest.Node\"\x19\x8a\x97\"\x15\n" +
	"\x03GET\x12\v/nodes/:num\"\x01*\x12u\n" +
	"\x10ListNodeMessages\x12\x19.rest.ListMessagesRequest\x1a\x1a.rest.ListMessagesResponse\"*\x8a\x97\"&\n" +
	"\x03GET\x12\x14/nodes/:num/messages\"\t.messages\x12k\n" +
	"\x0fSendNodeMessage\x12\x18.rest.SendMessageRequest\x1a\x16.google.protobuf.Empty\"&\x8a\x97\"\"\n" +
	"\x04POST\x12\x14/nodes/:num/messages\x1a\x01*(\xca\x01\x12f\n" +
	"\fListChannels\x12\x19.rest.ListChannelsRequest\x1a\x1a.rest.ListChannelsResponse\"\x1f\x8a\x97\"\x1b\n" +
	"\x03GET\x12\t/channels\"\t.channels\x12|\n" +
	"\x13ListChannelMessages\x12 .rest.ListChannelMessagesRequest\x1a\x1a.rest.ListMessagesResponse\"'\x8a\x97\"#\n" +
	"\x03GET\x12\x19/channels/:index/messages\"\x01*\x12z\n" +
	"\x12SendChannelMessage\x12\x1f.rest.SendChannelMessageRequest\x1a\x16.google.protobuf.Empty\"+\x8a\x97\"'\n" +
	"\x04POST\x12\x19/channels/:index/messages\x1a\x01*(\xca\x01\x1a\r\x92\x97\"\t\n" +
	"\a/api/v12\xd1\x02\n" +
	"\x0fCallbackService\x12f\n" +
	"\x10RegisterCallback\x12\x1d.rest.RegisterCallbackRequest\x1a\x16.google.protobuf.Empty\"\x1b\x8a\x97\"\x17\n" +
	"\x04POST\x12\t/callback\x1a\x01*(\xc9\x01\x12a\n" +
	"\rListCallbacks\x12\x1a.rest.ListCallbacksRequest\x1a\x1b.rest.ListCallbacksResponse\"\x17\x8a\x97\"\x13\n" +
	"\x03GET\x12\t/callback\"\x01*\x12d\n" +
	"\x0eDeleteCallback\x12\x1b.rest.DeleteCallbackRequest\x1a\x16.google.protobuf.Empty\"\x1d\x8a\x97\"\x19\n" +
	"\x06DELETE\x12\t/callback\x1a\x01*(\xcc\x01\x1a\r\x92\x97\"\t\n" +
	"\a/api/v1B%Z#github.com/loranode/gateway/api;apib\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gateway_proto_goTypes = []any{
	(*Node)(nil),                       // 0: rest.Node
	(*NodeSummary)(nil),                // 1: rest.NodeSummary
	(*Message)(nil),                    // 2: rest.Message
	(*ListNodesRequest)(nil),           // 3: rest.ListNodesRequest
	(*ListNodesResponse)(nil),          // 4: rest.ListNodesResponse
	(*GetNodeRequest)(nil),             // 5: rest.GetNodeRequest
	(*ListMessagesResponse)(nil),       // 6: rest.ListMessagesResponse
	(*ListMessagesRequest)(nil),        // 7: rest.ListMessagesRequest
	(*SendMessageRequest)(nil),         // 8: rest.SendMessageRequest
	(*RegisterCallbackRequest)(nil),    // 9: rest.RegisterCallbackRequest
	(*ListCallbacksRequest)(nil),       // 10: rest.ListCallbacksRequest
	(*ListCallbacksResponse)(nil),      // 11: rest.ListCallbacksResponse
	(*DeleteCallbackRequest)(nil),      // 12: rest.DeleteCallbackRequest
	(*Channel)(nil),                    // 13: rest.Channel
	(*ListChannelsRequest)(nil),        // 14: rest.ListChannelsRequest
	(*ListChannelsResponse)(nil),       // 15: rest.ListChannelsResponse
	(*ListChannelMessagesRequest)(nil), // 16: rest.ListChannelMessagesRequest
	(*SendChannelMessageRequest)(nil),  // 17: rest.SendChannelMessageRequest
	(*emptypb.Empty)(nil),              // 18: google.protobuf.Empty
}
var file_gateway_proto_depIdxs = []int32{
	1,  // 0: rest.ListNodesResponse.nodes:type_name -> rest.NodeSummary
	2,  // 1: rest.ListMessagesResponse.messages:type_name -> rest.Message
	13, // 2: rest.ListChannelsResponse.channels:type_name -> rest.Channel
	3,  // 3: rest.MeshService.ListNodes:input_type -> rest.ListNodesRequest
	5,  // 4: rest.MeshService.GetNode:input_type -> rest.GetNodeRequest
	7,  // 5: rest.MeshService.ListNodeMessages:input_type -> rest.ListMessagesRequest
	8,  // 6: rest.MeshService.SendNodeMessage:input_type -> rest.SendMessageRequest
	14, // 7: rest.MeshService.ListChannels:input_type -> rest.ListChannelsRequest
	16, // 8: rest.MeshService.ListChannelMessages:input_type -> rest.ListChannelMessagesRequest
	17, // 9: rest.MeshService.SendChannelMessage:input_type -> rest.SendChannelMessageRequest
	9,  // 10: rest.CallbackService.RegisterCallback:input_type -> rest.RegisterCallbackRequest
	10, // 11: rest.CallbackService.ListCallbacks:input_type -> rest.ListCallbacksRequest
	12, // 12: rest.CallbackService.DeleteCallback:input_type -> rest.DeleteCallbackRequest
	4,  // 13: rest.MeshService.ListNodes:output_type -> rest.ListNodesResponse
	0,  // 14: rest.MeshService.GetNode:output_type -> rest.Node
	6,  // 15: rest.MeshService.ListNodeMessages:output_type -> rest.ListMessagesResponse
	18, // 16: rest.MeshService.SendNodeMessage:output_type -> google.protobuf.Empty
	15, // 17: rest.MeshService.ListChannels:output_type -> rest.ListChannelsResponse
	6,  // 18: rest.MeshService.ListChannelMessages:output_type -> rest.ListMessagesResponse
	18, // 19: rest.MeshService.SendChannelMessage:output_type -> google.protobuf.Empty
	18, // 20: rest.CallbackService.RegisterCallback:output_type -> google.protobuf.Empty
	11, // 21: rest.CallbackService.ListCallbacks:output_type -> rest.ListCallbacksResponse
	18, // 22: rest.CallbackService.DeleteCallback:output_type -> google.protobuf.Empty
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[2].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[8].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
